### ISSUE TITLE
compilation error, godot 3.0 - linux mint 18

### ISSUE THREAD

**Issue by frankiezafe** [djiamnot/gdosc#1]
at modules/gdosc/utils.cpp:

```
modules/gdosc/utils.cpp:6:47: error: explicit qualification in declaration of 'std::__cxx11::string utils::gdStringToString(String)'
   std::string utils::gdStringToString(String s) {
```

it seems related to namespace "utils"... (https://stackoverflow.com/questions/8461832/explicit-qualification-in-declaration#8461857)

**Comment by djiamnot** [comment]
are you compiling with `use_llvm=yes`?

**Comment by frankiezafe** [comment]
nope, with gcc, but the bug is gone after cleaning up everything and recompilation on my workstation :) - by the way, i've tested the demo, and everything is fine! great job!
