### ISSUE TITLE
Can't configure the message  to send.

### ISSUE THREAD

**Issue by LeLieuMultiple** [djiamnot/gdosc#11]
Hello there, thank you for the work done !
I'm trying to connect SonicPi to Godot using this module.
It works fine when sending datas from SonicPi to Godot, but in the other way, Godot to SonicPi, I can't configure the message correctly, and can only receive a "/osc/#bundle" message without arguments. Here is my OSCsender script :
```
extends OSCsender

var time = 0
var parent = null

func _ready():
	set_process( true )

func _process(delta):
	time += delta
	if time > 5:
		if (parent == null):
			return
		time  = 0
		msg_address("/osc/beat_switch")
		msg_add_int( 2 )
		msg_add_int( 22 )
		msg_add_string( "test" )
		msg_send()
		print("ok")
```
The code looks ok to me but doesn't change the received message. It looks like msg_adress(), add_int() and add_string() have no effects. IP and port are ok since I can see the "/osc/#bundle" message from SonicPi.

**Comment by djiamnot** [comment]
Strange, bundles are not even implemented in gdosc. Perhaps SonicPi expects bundles? I don't know that software. Printing the message with `oscdump` works for me. 

Here's a modified script (I got rid of the `parent` check):

```python
extends OSCsender
var time = 0
func _ready():
	set_process( true )

func _process(delta):
	time += delta
	if time > 5:
		msg_address("/osc/beat_switch")
		msg_add_int( 2 )
		msg_add_int( 22 )
		msg_add_string( "test" )
		msg_send()
		time = 0
```

and with oscdump I get `dedb71ee.7682730b /osc/beat_switch iis 2 22 "test"`

**Comment by djiamnot** [comment]
Please disregard my previous comment. 
Your code works fine when tested with `oscdump` (available from liblo-tools package). It is also known to work with SuperCollider and Pure Data. I don't know SonicPi so I cannot help there but will try look into to make sure that everything is correct on gdosc side.

**Comment by LeLieuMultiple** [comment]
You are totally right, `oscdump` allows me to get the OSC message sent by Godot with correct addressing and arguments, so the problem seems to come from the SonicPi setup rather than your module. 
I guess this is an other argument in favor of SuperCollider, as SP is just a Ruby program built on top of it.
Tyvm :) .
