### ISSUE TITLE
Deprecated can_build signature in config.py

### ISSUE THREAD

**Issue by SpotlightKid** [djiamnot/gdosc#13]
I get the following warning when compiling for latest Godot from git (3.1.x):

 > Warning: module 'gdosc' uses a deprecated `can_build` signature in its config.py file, it should be `can_build(env, platform)`.

**Comment by djiamnot** [comment]
Thanks, updated in _develop_ branch

**Comment by jmpetroske** [comment]
This breaks building for versions before that for godot, but its easy to change it back to `can_build(env, platform)`. Perhaps there should be some discussion about how to keep different versions of godot modules for different godot versions?

**Comment by djiamnot** [comment]
With the plans to port to GDNative (which has already started https://gitlab.com/frankiezafe/gdnative_osc), I don't think I will be keeping the module afloat. Godot >3 seems to be the way of the future ;) But I'm interested to know of any arguments in favour of using GD 2.x these days.

**Comment by jmpetroske** [comment]
Yeah I agree. It just didn't build for me on 3.0.6 (the latest stable) without changing it. But yeah sounds like its not work any thought
